# Generated by Django 5.0.7 on 2024-08-06 09:17

import django.db.models.deletion
from django.db import migrations, models

import qlued.models


class Migration(migrations.Migration):

    dependencies = [
        ("qlued", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="storage_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qlued.storageproviderdb",
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="uuid_hex",
            field=qlued.models.UUIDHexField(
                blank=True, max_length=24, null=True, unique=True
            ),
        ),
    ]
