# Generated by Django 5.1 on 2024-08-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qlued", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="storage_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qlued.storageproviderdb",
            ),
        ),
    ]
